name: garasin
description: GarasiIn - Marketplace Sewa Garasi Rumah untuk Parkir Mobil.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management & routing
  get: ^4.6.6

  # Icons
  iconsax: ^0.0.8

  # Date & currency formatting
  intl: ^0.19.0

  # Signature pad for digital signature
  signature: ^5.4.0

  # Image picker for profile photo
  image_picker: ^1.0.7

  # SQLite local database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # Session management
  shared_preferences: ^2.2.2

  # Password hashing
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
