name: garasin
description: GarasiIn - Marketplace Sewa Garasi Rumah untuk Parkir Mobil.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management & routing
  flutter_test:
    sdk: flutter
  get: ^4.6.6

  # Icons
  iconsax: ^0.0.8

  # Date & currency formatting
  intl: ^0.19.0

  # Signature pad for digital signature
  signature: ^5.4.0

  # Image picker for profile photo
  image_picker: ^1.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
